version: '3'

services:
    nginx:
        image: nginx:1.19
        ports:
            - 8080:80
        volumes:
            - ./web:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    php:
        image: php:7.4-fpm
        volumes:
            - ./web:/usr/share/nginx/html
        environment:
            - FLAG='ITF{d3adlyBugInPHP}'
